# !/bin/bash
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD1 device UP SOFT 1
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD2 device UP SOFT 2
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD3 device UP SOFT 3
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD4 device UP SOFT 4
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD5 device UP SOFT 5
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD6 device UP SOFT 6
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD7 device UP SOFT 7
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD8 device UP SOFT 8
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD9 device UP SOFT 9
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD10 device UP SOFT 10
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD11 device DOWN SOFT 1
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD12 device DOWN SOFT 2
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD13 device DOWN SOFT 3
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD14 device DOWN SOFT 4
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD15 device DOWN SOFT 5
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD16 device DOWN SOFT 6
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD17 device DOWN SOFT 7
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD18 device DOWN SOFT 8
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD19 device DOWN SOFT 9
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD20 device DOWN SOFT 10
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD21 device UNREACHABLE SOFT 1
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD22 device UNREACHABLE SOFT 2
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD23 device UNREACHABLE SOFT 3
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD24 device UNREACHABLE SOFT 4
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD25 device UNREACHABLE SOFT 5
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD26 device UNREACHABLE SOFT 6
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD27 device UNREACHABLE SOFT 7
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD28 device UNREACHABLE SOFT 8
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD29 device UNREACHABLE SOFT 9
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD30 device UNREACHABLE SOFT 10
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD31 device UP HARD 1
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD32 device UP HARD 2
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD33 device UP HARD 3
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD34 device UP HARD 4
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD35 device UP HARD 5
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD36 device UP HARD 6
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD37 device UP HARD 7
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD38 device UP HARD 8
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD39 device UP HARD 9
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD40 device UP HARD 10
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD41 device DOWN HARD 1
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD42 device DOWN HARD 2
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD43 device DOWN HARD 3
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD44 device DOWN HARD 4
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD45 device DOWN HARD 5
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD46 device DOWN HARD 6
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD47 device DOWN HARD 7
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD48 device DOWN HARD 8
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD49 device DOWN HARD 9
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD50 device DOWN HARD 10
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD51 device UNREACHABLE HARD 1
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD52 device UNREACHABLE HARD 2
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD53 device UNREACHABLE HARD 3
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD54 device UNREACHABLE HARD 4
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD55 device UNREACHABLE HARD 5
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD56 device UNREACHABLE HARD 6
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD57 device UNREACHABLE HARD 7
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD58 device UNREACHABLE HARD 8
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD59 device UNREACHABLE HARD 9
/usr/bin/php /usr/local/nagios/etc/utils/nagios_send_host.php PAYLOAD60 device UNREACHABLE HARD 10
